#! /bin/sh

# lsgithub

# Last update: Tue Aug  6 10:13:40 JST 2019 by hohno

jq=/usr/local/bin/jq

[ -x "$jq" ] || exit 1

GITHUB_USER=hohno-46466

if [ "x$1" = "x-t" ]; then
    CMD="sort -k3,3 -k4,4"
elif [ "x$1" = "x-c" ]; then
    CMD="sort -k1,1 -k2,2"
else
    CMD="cat"
fi

curl -s "https://api.github.com/users/${GITHUB_USER}/repos?per_page=100" \
    | jq '.[] | .created_at, .updated_at, .name'  \
    | awk '{{printf "%s  ",$0};if ((NR % 3) == 0){printf "\n"}}'  \
    | sed -e 's/"//g'  -e 's/\(-[0-9][0-9]\)T\([0-9][0-9]:\)/\1 \2/g' -e 's/Z  /  /g'  \
    | $CMD

# echo ""
echo "# open https://github.com/$GITHUB_USER to reach repositories above."
echo "# You can NOT try this command more than 60 times per an hour."
# echo ""
